[package]
name = "parse_sheet_from_weixin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest  = "0.11.13"
scraper = "0.14.0"
