[package]
name = "parse_sheet_from_weixin"
version = "1.0.0"
edition = "2021"

[lints.clippy]
all = "deny"
pedantic = "deny"
#cargo = "deny"
#restriction = "deny"
#nursery = "deny"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.75"
json = "0.12.4"
log = "0.4.17"
pretty_env_logger = "0.4.0"
regex = "1.7.0"
reqwest  = "0.11.13"
scraper = "0.14.0"
thirtyfour = "0.31.0"
thiserror = "1.0.50"
tokio = { version = "1.38.0", features = ["full"] }
